name: Update Profile Views (Simple Counter)

# Alternative version that maintains a simple incrementing counter
# instead of using GitHub Traffic API
# This version counts every run, not actual traffic

on:
  # Trigger on profile README views (requires webhook setup)
  # or run on schedule
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update counter
        id: counter
        run: |
          # File to store count
          COUNT_FILE=".github/views-count.txt"

          # Create file if doesn't exist
          if [ ! -f "$COUNT_FILE" ]; then
            echo "125" > "$COUNT_FILE"  # Start from current komarev count
          fi

          # Read current count
          CURRENT=$(cat "$COUNT_FILE")

          # Increment (this is naive - increments on each run, not actual views)
          # For demo purposes only
          NEW=$((CURRENT + 1))

          echo "$NEW" > "$COUNT_FILE"
          echo "count=$NEW" >> $GITHUB_OUTPUT

          echo "Updated count from $CURRENT to $NEW"

      - name: Generate badge
        run: |
          COUNT="${{ steps.counter.outputs.count }}"
          mkdir -p .github

          # Using shields.io static badge
          curl -o .github/profile-views.svg \
            "https://img.shields.io/badge/PROFILE_VIEWS-${COUNT}-00C7B7?style=for-the-badge"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .github/

          if ! git diff --staged --quiet; then
            git commit -m "Update profile views: ${{ steps.counter.outputs.count }} [skip ci]"
            git push
          fi

# NOTE: This is a simplified version that doesn't accurately count views
# It just increments on each scheduled run
# For accurate view counting, use the GitHub Traffic API version
# or the self-hosted serverless solution
